### ISSUE TITLE
Invalid image data while decoding blurhash data

### ISSUE THREAD

**Issue by haashem** [justacid/blurhash-dart#13] opened 2021-04-08 09:07 UTC
In Flutter context, I try to decode blurhash string to image, but it throws exception `Exception: Invalid image data
`
any idea what's wrong?
I copied the blur hash string from https://blurha.sh 

```dart
Widget build(BuildContext context) {
  final image = BlurHash.decode('LEHV6nWB2yk8pyo0adR*.7kCMdnj').toImage(32, 32);
  return Image.memory(image.getBytes());
}
```

**Comment by justacid** [comment] 2021-04-12 12:12
Hi,

the problem is that `Image.memory` does not expect raw bytes, but a jpeg, png, etc. Instead of passing the bytes directly, you have to encode the image beforehand, like so:

```dart
Widget build(BuildContext context) {
  final image = BlurHash.decode('LEHV6nWB2yk8pyo0adR*.7kCMdnj').toImage(32, 32);
  return Image.memory(Uint8List.fromList(encodeJpg(image)));
}
```

Don't forget to depend on and import the 'image' library to get access to `encodeJpg`. Btw I'd recommend to put the decoding in a stateful widget, so you don't have to decode the hash on every build-call.

**Comment by haashem** [comment] 2021-04-13 07:06
Thanks a lot for clarifying. I suggest to add above hint in Readme. otherwise most Flutter use will have my issue because they don't know they have to encode Raw data to image.

**Comment by justacid** [comment] 2021-04-13 11:44
No problem. :)
 
Good idea! I added a note on Flutter to the readme: https://github.com/justacid/blurhash-dart/blob/master/README.md#note-usage-with-flutter and I'm closing this issue.

**Closed as completed by justacid** 2021-04-13 11:44 UTC
